packages:
  - 'apps/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
