packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  react: 19.2.4
  react-dom: 19.2.4
