// 食材资料（Phase 8-1 / ADR-0018）：这是**发布输入**，经人工审核后由
// `pnpm ingredients:import` 写入数据库；已发布列表与详情一律从数据库读取。
//
// 审核纪律（逐条核对，不凭字面猜测）：
// - 规范名称是展示主名；`aliases` 只放**同物异名**（番茄／西红柿），
//   相近、可替代、上下位原料不合并（鸡蛋≠鸭蛋、生抽≠老抽、豆腐≠大豆）。
// - 加工食品（酱料、罐头、成品咖喱块等）按 `allergens` 显式列出**可核查**的成分过敏原，
//   并给出来源；没有可靠依据时留空数组，空数组表示「信息不足」，不是「确认不含」。
// - 无可靠依据的可选段落直接省略，不编造（尤其保存时长）。
// - 来源均为可核查页面（国家食品安全标准、USDA FoodData Central、食品企业公开配料页、
//   消费者协会科普页等）。措辞统一走通用参考入口，不虚构具体标题与日期。
//
// - 每条 `reviewedAt` 是维护者**逐条复核**的时间；缺失表示尚未复核，
//   导入后数据库该行 `reviewedAt` 为 null（列表/详情据此显示「未复核」）。
//
// 未列入本文件的原料在归一阶段被拒绝（`scripts/import-ingredients.ts` 明确报错），
// 不会静默创建残缺身份。
import type { IngredientCategory } from '../../generated/prisma/client';

export type ReviewedIngredient = {
  /** 规范名称（展示主名） */
  name: string;
  /** 同物异名，指向同一身份 */
  aliases?: string[];
  category: IngredientCategory;
  /** 当前菜谱库中各写法与之指向同一身份（归一表，逐条人工确认） */
  rawNames: string[];
  /** 经人工审核的简介 */
  summary: string;
  selection?: string;
  storage?: string;
  preparation?: string;
  /** 可核查参考来源；空数组不允许 */
  sources: string[];
  /**
   * 维护者逐条复核时间（ISO 字符串）。没有这一项 = 尚未复核，
   * 导入时写入 `reviewedAt = null`，数据库行不会声称「已审核」。
   */
  reviewedAt?: string;
  /** 已核查的成分过敏原；未知留空，不用空数组表达「确认不含」 */
  allergens?: { allergen: string; source: string }[];
};

/** 通用参考入口（可核查、稳定） */
const SRC = {
  usda: 'https://fdc.nal.usda.gov/',
  gbStandards: 'https://sppt.cfsa.net.cn:8086/db',
  cfsa: 'https://www.cfsa.net.cn/',
} as const;

const allerg = (allergen: string, source: string = SRC.cfsa) => ({
  allergen,
  source,
});

/** 水产类通用过敏原（鱼类、甲壳类、软体类按 USDA/CFSA 分类核查） */
const FISH = allerg('鱼类');
const SHELLFISH = allerg('甲壳类');
const MOLLUSK = allerg('软体动物');

export const REVIEWED_INGREDIENTS: ReviewedIngredient[] = [
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '番茄',
    aliases: ['西红柿'],
    category: 'VEGETABLE',
    rawNames: ['番茄', '小番茄', '樱桃番茄'],
    summary:
      '茄科果实类蔬菜，生吃清甜、加热后风味更浓。小番茄（圣女果）与普通番茄风味接近，可按同一食材使用，此处不区分大小。',
    selection: '表皮紧实有光泽、手感沉、蒂部新鲜；避免明显软塌或开裂。',
    storage: '常温阴凉处短放；切开后需冷藏并尽快食用。',
    preparation: '顶部划十字后用热水烫一下更容易去皮；去蒂后按菜谱切块或打汁。',
    sources: ['https://fdc.nal.usda.gov/', 'https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '四季豆',
    aliases: ['豆角', '芸豆'],
    category: 'VEGETABLE',
    rawNames: ['四季豆'],
    summary: '豆科嫩荚蔬菜，脆嫩清甜，常用于炒制或焖煮。',
    selection: '豆荚饱满挺直、折断脆响、无锈斑与虫孔。',
    storage: '装袋冷藏；放置过久易纤维化。',
    preparation: '掐去两端与两侧老筋，折段；必须彻底加热至熟透后再食用。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '土豆',
    aliases: ['马铃薯'],
    category: 'VEGETABLE',
    rawNames: ['土豆'],
    summary: '块茎类蔬菜，淀粉含量高，可炒、炖、炸或压泥。',
    selection: '表皮完整、无芽眼与青皮、手感坚实。',
    storage: '阴凉避光通风处散放；避光可减少表皮发绿。',
    preparation: '去皮后切块或切丝；切丝后可冲水去表面淀粉。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '胡萝卜',
    category: 'VEGETABLE',
    rawNames: ['胡萝卜'],
    summary: '根茎类蔬菜，甜味明显，常用于炖煮、快炒或凉拌。',
    selection: '表面光滑、颜色均匀、手感硬挺。',
    storage: '装袋冷藏，去掉缨部可延长保存。',
    preparation: '去皮后按需要切丝、切片或滚刀块。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '洋葱',
    category: 'VEGETABLE',
    rawNames: ['洋葱'],
    summary: '葱属鳞茎蔬菜，炒制后甜味突出，是多数西式与日式炖菜的底味。',
    selection: '外皮干燥紧实、颈部收紧、手感沉。',
    storage: '阴凉干燥通风处悬挂或散放。',
    preparation: '切去两端去皮；切丝或切丁，切后易氧化，尽快下锅。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '紫洋葱',
    category: 'VEGETABLE',
    rawNames: ['紫洋葱'],
    summary: '洋葱的紫皮品种，辛香更冲，适合凉拌与生食配菜。',
    selection: '外皮紧实有光泽、无soft spot。',
    storage: '阴凉干燥通风处散放。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '大葱',
    aliases: ['京葱'],
    category: 'VEGETABLE',
    rawNames: ['大葱'],
    summary: '葱属植物，葱白与葱叶均可入菜，爆香与提味常用。',
    selection: '葱白紧实、叶片挺立不发黄。',
    storage: '冷藏保存；切段后可冷冻备用。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '葱',
    aliases: ['小葱', '香葱'],
    category: 'VEGETABLE',
    rawNames: ['葱', '小葱', '葱花', '葱段', '葱丝'],
    summary:
      '细香葱，多用作提香与点缀。切碎、切段、切丝是同一食材的不同处理形式。',
    selection: '叶片翠绿挺立、根部洁白不发黏。',
    storage: '冷藏；洗净沥干后切碎冷冻可延长使用。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '生姜',
    aliases: ['姜'],
    category: 'VEGETABLE',
    rawNames: ['姜', '姜片', '姜末'],
    summary:
      '姜科根茎，辛香去腥，既是调味也可作辅料。切片、切末、磨泥是同一食材的不同处理形式。',
    selection: '表皮紧实不皱、断面纤维细、香气明显。',
    storage: '干燥阴凉处短放；冷藏或冷冻可延长。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '大蒜',
    aliases: ['蒜'],
    category: 'VEGETABLE',
    rawNames: ['大蒜', '蒜', '蒜末'],
    summary:
      '葱属鳞茎，爆香后风味突出。整瓣、切片、切末是同一食材的不同处理形式。',
    selection: '蒜瓣饱满紧实、无发芽与霉斑。',
    storage: '阴凉干燥通风处散放；剥好的蒜末可冷藏数日。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '青椒',
    category: 'VEGETABLE',
    rawNames: ['青椒'],
    summary: '未成熟甜椒或微辣品种，脆嫩，常用于快炒。',
    selection: '表皮光亮、手感硬挺、蒂部鲜绿。',
    storage: '冷藏保存，避免挤压。',
    preparation: '去籽去筋后切丝或切块。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '彩椒',
    aliases: ['甜椒'],
    category: 'VEGETABLE',
    rawNames: ['彩椒', '红甜椒'],
    summary:
      '成熟甜椒，甜味明显、口感脆，常用于烤制与生食。红甜椒为其中一种颜色品种。',
    selection: '表皮光亮、肉质厚、手感沉。',
    storage: '冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '包菜',
    aliases: ['卷心菜', '圆白菜'],
    category: 'VEGETABLE',
    rawNames: ['包菜', '卷心菜'],
    summary: '结球甘蓝，耐炒耐煮，是家常小炒的常见原料。',
    selection: '叶球紧实、外叶无腐烂与虫孔。',
    storage: '冷藏；切开后用保鲜膜包住断面。',
    preparation: '去掉外层老叶，手撕或切丝。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '菠菜',
    category: 'VEGETABLE',
    rawNames: ['菠菜'],
    summary: '苋科叶菜（俗称菠菜），草酸含量较高，焯水后口感更柔和。',
    selection: '叶片挺立翠绿、根部饱满不发黏。',
    storage: '冷藏，趁新鲜食用。',
    preparation: '洗净后焯水再炒或凉拌。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '生菜',
    aliases: ['莴苣叶'],
    category: 'VEGETABLE',
    rawNames: ['生菜', '生菜叶', '混合生菜', '罗马生菜'],
    summary:
      '菊科叶菜，脆嫩多用于生食、卷食与沙拉。罗马生菜叶形长而挺立，属同一食材的不同品种。',
    selection: '叶片挺立、边缘无褐变。',
    storage: '冷藏；洗净后需沥干再存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '黄瓜',
    category: 'VEGETABLE',
    rawNames: ['黄瓜'],
    summary: '葫芦科果实，水分高、口感脆，适合凉拌与快炒。',
    selection: '表皮带刺有弹性、两端不软。',
    storage: '冷藏，避免与番茄长期同放。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '西葫芦',
    category: 'VEGETABLE',
    rawNames: ['西葫芦'],
    summary: '葫芦科瓜类，肉质细嫩，适合快炒、烤制或擦丝做饼。',
    selection: '表皮光滑发亮、手感沉、指甲轻掐能留痕。',
    storage: '冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '南瓜',
    category: 'VEGETABLE',
    rawNames: ['南瓜'],
    summary: '葫芦科瓜类，甜味明显，适合蒸、炖或做汤。',
    selection: '表皮硬实、瓜柄干燥、切面颜色深。',
    storage: '整只阴凉处存放；切开后冷藏。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '茄子',
    category: 'VEGETABLE',
    rawNames: ['茄子'],
    summary: '茄科果实，吸油明显，常用于红烧与快炒。',
    selection: '表皮光亮紧实、蒂部鲜绿、手感沉。',
    storage: '冷藏；切开后尽快使用。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '芹菜',
    category: 'VEGETABLE',
    rawNames: ['芹菜'],
    summary: '伞形科茎用蔬菜，香气明显，可炒可凉拌。',
    selection: '茎脆易折、叶片鲜绿。',
    storage: '冷藏，用保鲜膜包住茎部。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '蒜苗',
    aliases: ['蒜薹'],
    category: 'VEGETABLE',
    rawNames: ['蒜苗'],
    summary: '大蒜的嫩苗（蒜薹为抽薹期花茎），辛香清脆，常用于炒肉。',
    selection: '色泽鲜绿、茎部挺立易折。',
    storage: '冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '豆芽',
    category: 'VEGETABLE',
    rawNames: ['豆芽'],
    summary: '豆类萌发的嫩芽，脆嫩，快炒或做汤配料。',
    selection: '芽体洁白挺立、无异味与发黏。',
    storage: '冷藏，尽快食用。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '莲藕',
    aliases: ['藕'],
    category: 'VEGETABLE',
    rawNames: ['莲藕', '藕'],
    summary: '莲的根茎，可脆炒也可炖汤，切开后易氧化变褐。',
    selection: '藕节粗壮、表皮无黑斑、断面洁白。',
    storage: '冷藏；切开后用清水浸泡并尽快使用。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '白萝卜',
    category: 'VEGETABLE',
    rawNames: ['白萝卜', '白萝卜泥'],
    summary: '十字花科根菜，清甜微辛，可炖可腌，磨泥多用于日式配菜。',
    selection: '表皮光滑、手感沉、无空心感。',
    storage: '阴凉处或冷藏；切开后包住断面。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '香菇',
    category: 'VEGETABLE',
    rawNames: ['香菇'],
    summary: '常见食用菌，鲜香浓郁，可炒、炖或做汤底。',
    selection: '菌盖厚实内卷、菌褶紧密、无黏液。',
    storage: '冷藏；用纸袋比塑料袋更不易积水。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '口蘑',
    aliases: ['白蘑菇'],
    category: 'VEGETABLE',
    rawNames: ['口蘑', '白蘑菇'],
    summary: '白色双孢蘑菇，味道温和，适合炒、烤与奶油类酱汁。',
    selection: '菌盖洁白紧实、切口无褐变。',
    storage: '冷藏，避免清洗后久放。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '木耳',
    aliases: ['黑木耳'],
    category: 'VEGETABLE',
    rawNames: ['木耳', '干木耳'],
    summary: '木耳科食用菌，干品需泡发后使用，口感脆爽。',
    selection: '干品朵形完整、无霉斑与虫蛀。',
    storage: '干品密封防潮常温存放；泡发后冷藏并尽快用掉。',
    preparation: '冷水泡发至完全柔软，摘去根蒂，焯水后再炒。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '玉米粒',
    aliases: ['甜玉米粒'],
    category: 'VEGETABLE',
    rawNames: ['玉米粒', '甜玉米粒（罐头或冷冻）'],
    summary: '甜玉米的籽粒，罐装或冷冻成品可直接使用，常用作配菜。',
    selection: '颗粒饱满、色泽均匀。',
    storage: '罐头开罐后冷藏并尽快使用；冷冻品保持冷冻。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '青豆',
    category: 'VEGETABLE',
    rawNames: ['青豆'],
    summary: '未成熟豌豆或青豌豆籽粒，清甜，常用作配菜。',
    selection: '颗粒饱满、颜色翠绿。',
    storage: '冷冻或冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '牛蒡',
    category: 'VEGETABLE',
    rawNames: ['牛蒡'],
    summary: '菊科根菜，纤维明显、香气特殊，日式料理常见。',
    selection: '表皮完整、手感硬、无软化。',
    storage: '冷藏；切开后浸水防氧化。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '欧芹',
    aliases: ['洋香菜'],
    category: 'VEGETABLE',
    rawNames: ['欧芹'],
    summary: '伞形科香草，气味清新，多用于西餐点缀与提香。',
    selection: '叶片翠绿挺立、茎部不发黄。',
    storage: '冷藏；切碎后冷冻可久存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '罗勒',
    aliases: ['九层塔'],
    category: 'VEGETABLE',
    rawNames: ['罗勒'],
    summary: '唇形科香草，香气浓郁，常用于意面与沙拉。',
    selection: '叶片完整翠绿、无黑斑。',
    storage: '冷藏；避免低温冻伤。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '迷迭香',
    category: 'VEGETABLE',
    rawNames: ['迷迭香'],
    summary: '唇形科木质香草，香气浓烈，适合烤制与炖煮。',
    selection: '枝条挺立、针叶翠绿。',
    storage: '冷藏或风干保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '牛油果',
    aliases: ['鳄梨'],
    category: 'VEGETABLE',
    rawNames: ['牛油果'],
    summary: '樟科果实，口感绵密，多用于沙拉与轻食。',
    selection: '轻按果蒂略软即熟；过硬需常温后熟。',
    storage: '未熟常温后熟，成熟后冷藏。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '酸菜',
    category: 'VEGETABLE',
    rawNames: ['酸菜'],
    summary: '经乳酸发酵的白菜类制品，酸香开胃，常用于炖煮。',
    selection: '气味酸香无异味、菜体完整。',
    storage: '冷藏保存，取用时保持器具洁净。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '五花肉',
    category: 'MEAT',
    rawNames: ['五花肉'],
    summary: '猪腹部肉，肥瘦相间，适合红烧、回锅与慢炖。',
    selection: '肥瘦分层清晰、肉质有弹性。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '猪肉末',
    aliases: ['肉末'],
    category: 'MEAT',
    rawNames: ['猪肉末'],
    summary: '绞碎的猪肉，受热快、易入味，常用于麻婆豆腐一类菜肴。',
    selection: '颜色鲜红、无渗水与异味。',
    storage: '冷藏 1–2 天内用完或冷冻保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '猪肉片',
    category: 'MEAT',
    rawNames: ['猪肉片'],
    summary: '切片的猪肉，适合快炒与火锅。',
    selection: '颜色均匀、纹理清晰。',
    storage: '冷藏短期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '猪里脊',
    aliases: ['里脊肉'],
    category: 'MEAT',
    rawNames: ['猪里脊', '猪里脊片', '猪里脊肉', '猪瘦肉'],
    summary: '猪脊部瘦肉，纤维细、口感嫩，适合切丝切片的快炒。',
    selection: '色泽浅红、切面干爽。',
    storage: '冷藏短期、冷冻长期保存。',
    preparation: '顺纹切片、逆纹切丝；抓淀粉可保持嫩度。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '排骨',
    category: 'MEAT',
    rawNames: ['排骨'],
    summary: '带骨猪肉，骨髓丰富，适合炖煮与蒸制。',
    selection: '骨肉比例匀称、肉质粉红。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '午餐肉',
    category: 'MEAT',
    rawNames: ['午餐肉'],
    summary: '罐装猪肉重组制品，咸香，多用于煎制与炒饭。',
    selection: '罐体无膨胀变形、开罐后气味正常。',
    storage: '开罐后冷藏并尽快食用。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '培根',
    category: 'MEAT',
    rawNames: ['培根'],
    summary: '烟熏或腌制的猪腹肉切片，咸香，多用于煎制与配菜。',
    selection: '切片完整、脂肪洁不黄。',
    storage: '冷藏保存，开封后尽快食用。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '大豆', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '火腿片',
    category: 'MEAT',
    rawNames: ['火腿片'],
    summary: '腌制的猪后腿肉切片，可生食或加热，常用于三明治与拼盘。',
    selection: '色cai泽均匀、无异味。',
    storage: '冷藏保存，开封后尽快食用。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '牛腩',
    category: 'MEAT',
    rawNames: ['牛腩'],
    summary: '牛腹部带筋膜的肉，久炖后软糯，适合炖菜。',
    selection: '肉色深红、筋膜分布均匀。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '牛腱子肉',
    category: 'MEAT',
    rawNames: ['牛腱子肉'],
    summary: '牛腿部肌肉，筋络多、口感紧实，适合卤制与久炖。',
    selection: '筋膜清晰、切面有光泽。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '牛里脊肉',
    aliases: ['牛柳'],
    category: 'MEAT',
    rawNames: ['牛里脊肉'],
    summary: '牛脊部瘦肉，纤维细嫩，适合快炒与煎制。',
    selection: '颜色鲜红、纹理细密。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '牛排',
    category: 'MEAT',
    rawNames: ['牛排（西冷或眼肉）'],
    summary:
      '厚切牛肉排，西冷（外脊）与眼肉（肋眼）部位不同、口感不同：西冷带侧边脂肪、嚼劲更足，眼肉脂肪分布更均匀。二者可互相替代，不视为同一部位，替换后用量与火候需相应调整。',
    selection: '脂肪分布均匀、颜色鲜红、表面干爽。',
    storage: '冷藏短期、冷冻长期保存；煎前回温。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '薄切牛肉片',
    aliases: ['牛肉薄片'],
    category: 'MEAT',
    rawNames: ['薄切牛肉片', '牛肉薄片', '牛肉片'],
    summary: '切成薄片的牛肉，受热快，适合火锅与快炒。',
    selection: '切片完整、无连刀与碎末。',
    storage: '冷藏短期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '牛肉末',
    category: 'MEAT',
    rawNames: ['牛肉末'],
    summary: '绞碎的牛肉，易入味，适合做酱与馅料。',
    selection: '颜色鲜红、无渗水。',
    storage: '冷藏 1–2 天内用完或冷冻。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '牛肚',
    category: 'MEAT',
    rawNames: ['牛肚'],
    summary: '牛胃，口感脆韧，需长时间煮软后食用。',
    selection: '色泽洁白或淡黄、无异味。',
    storage: '冷藏或冷冻保存。',
    preparation: '充分清洗后长时间煮至软烂。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '毛肚',
    category: 'MEAT',
    rawNames: ['毛肚'],
    summary: '牛瘤胃（蜂巢肚）内壁，脆嫩，涮煮即可。',
    selection: '叶片厚实、颜色自然、无刺鼻气味。',
    storage: '冷藏并尽快食用。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '猪大肠',
    category: 'MEAT',
    rawNames: ['猪大肠'],
    summary: '猪肠道，需彻底清洗去腥后炖煮，口感软糯。',
    selection: '色泽浅、组织厚实、无异常气味。',
    storage: '冷藏或冷冻保存。',
    preparation: '翻面用盐与面粉反复搓洗，焯水后使用。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鸭血',
    category: 'MEAT',
    rawNames: ['鸭血'],
    summary: '鸭血凝固制品，质地细嫩，多用于火锅与汤品。',
    selection: '颜色暗红均匀、切面细滑无气孔过大。',
    storage: '冷藏保存，尽快食用。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '羊里脊肉',
    category: 'MEAT',
    rawNames: ['羊里脊肉'],
    summary: '羊脊部瘦肉，细嫩无筋，适合快炒与煎制。',
    selection: '颜色鲜红、脂肪洁白。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鸡腿肉',
    aliases: ['鸡腿'],
    category: 'POULTRY',
    rawNames: ['鸡腿肉', '鸡腿'],
    summary: '鸡腿部肉，脂肪与结缔组织较多，久煮不柴，适合煎、炖与盖饭。',
    selection: '表皮紧致、肉质有弹性、无异味。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鸡胸肉',
    aliases: ['鸡胸'],
    category: 'POULTRY',
    rawNames: ['鸡胸肉'],
    summary: '鸡胸部瘦肉，蛋白质含量高、脂肪低，适合煎、煮与沙拉。',
    selection: '色泽粉白、表面干爽无渗水。',
    storage: '冷藏短期、冷冻长期保存。',
    preparation: '厚块横剖成两片再煎可避免外老内生；盐腌可保持水分。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鸡翅中',
    aliases: ['鸡翅'],
    category: 'POULTRY',
    rawNames: ['鸡翅中'],
    summary: '鸡翅中段，皮厚肉嫩，适合煎烤与焖煮。',
    selection: '表皮完整、无淤血与异味。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鸡爪',
    category: 'POULTRY',
    rawNames: ['鸡爪'],
    summary: '鸡足部，胶质丰富，需久煮后食用。',
    selection: '色泽自然、无刺鼻药水味。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鸡蛋',
    category: 'EGG',
    rawNames: ['鸡蛋'],
    summary: '鸡蛋全蛋，是最常用的蛋类原料，可炒、蒸、煮与打发。',
    selection: '蛋壳完整无裂、摇晃无晃动感。',
    storage: '冷藏保存；大头朝上放置。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '蛋类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '蛋清',
    aliases: ['蛋白'],
    category: 'EGG',
    rawNames: ['蛋清'],
    summary: '分离出的鸡蛋清，常用于上浆、打发与蒸制。',
    storage: '冷藏，尽快使用。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '蛋类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '蛋黄',
    category: 'EGG',
    rawNames: ['蛋黄'],
    summary: '分离出的鸡蛋黄，脂肪与风味集中，常用于酱汁与烘焙。',
    storage: '冷藏，尽快使用。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '蛋类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '牛蛙',
    category: 'MEAT',
    rawNames: ['牛蛙'],
    summary: '蛙科两栖动物的可食部分，肉质细嫩紧实，需彻底加热后食用。',
    selection: '肉质紧实有弹性、无异味。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '猪肉馅',
    category: 'MEAT',
    rawNames: ['猪肉馅'],
    summary:
      '绞碎调味的猪肉糜，用于饺子、肉饼一类菜式；与猪肉末同属绞肉处理形式。',
    selection: '颜色鲜红、无渗水与异味。',
    storage: '冷藏 1–2 天内用完或冷冻保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '芦笋',
    category: 'VEGETABLE',
    rawNames: ['芦笋'],
    summary: '天门冬科嫩茎蔬菜，清甜脆嫩，快炒或烤制即可。',
    selection: '茎挺立、切口新鲜不发干、尖端紧密。',
    storage: '冷藏，切口可用湿纸包住。',
    preparation: '削去根部老皮，按需要切段。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '香菜',
    aliases: ['芫荽'],
    category: 'VEGETABLE',
    rawNames: ['香菜'],
    summary: '伞形科香草，气味独特，多用于提香与点缀。',
    selection: '叶片鲜绿挺立、根部不发黏。',
    storage: '冷藏保存，洗净后需沥干。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '三文鱼',
    aliases: ['鲑鱼'],
    category: 'SEAFOOD',
    rawNames: ['三文鱼', '三文鱼排'],
    summary:
      '鲑科鱼类，脂肪丰富、肉质橙红，可煎、烤或生食（生食需符合生食标准）。',
    selection: '肉色橙红均匀、脂肪纹清晰、无异味。',
    storage: '冷藏短期；生食须保持冷链并尽快食用。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '鱼类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鲈鱼',
    category: 'SEAFOOD',
    rawNames: ['鲈鱼'],
    summary: '常见食用鱼类，肉质细嫩少刺，适合清蒸。',
    selection: '鱼眼清亮、鳃鲜红、按压有弹性。',
    storage: '冷藏并尽快处理。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '鱼类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '草鱼',
    aliases: ['鲩鱼'],
    category: 'SEAFOOD',
    rawNames: ['草鱼'],
    summary: '淡水鲤科鱼类，肉质紧实，适合红烧与切片。',
    selection: '鱼鳃鲜红、鳞片完整。',
    storage: '冷藏并尽快处理。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '鱼类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '青花鱼',
    aliases: ['鲭鱼'],
    category: 'SEAFOOD',
    rawNames: ['青花鱼'],
    summary: '鲭科海鱼，脂肪含量高、风味浓，适合煎烤。',
    selection: '表皮银亮、肉质紧实。',
    storage: '冷藏并尽快食用。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '鱼类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鳕鱼',
    category: 'SEAFOOD',
    rawNames: ['鳕鱼块', '鳕鱼柳'],
    summary: '鳕科白肉鱼，肉厚刺少、味道清淡，适合煎、烤与炸。',
    selection: '肉质洁白有弹性、无发黄。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '鱼类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '金枪鱼罐头',
    aliases: ['吞拿鱼罐头'],
    category: 'SEAFOOD',
    rawNames: ['水浸金枪鱼罐头'],
    summary: '罐装金枪鱼，水浸或油浸，开封即用。',
    selection: '罐体无膨胀变形、开罐无异味。',
    storage: '开罐后冷藏并尽快食用。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '鱼类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '虾',
    aliases: ['鲜虾'],
    category: 'SEAFOOD',
    rawNames: ['基围虾', '大虾'],
    summary: '甲壳类水产，肉质弹嫩、受热快，适合白灼、快炒与蒸制。',
    selection: '壳体透亮、头身连接紧、无异味。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '甲壳类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '虾仁',
    category: 'SEAFOOD',
    rawNames: ['虾仁'],
    summary: '去壳的虾肉，受热快，常用于快炒、蒸蛋与沙拉。',
    selection: '肉质半透明有弹性、无氨味。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '甲壳类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鱿鱼',
    aliases: ['鱿鱼圈'],
    category: 'SEAFOOD',
    rawNames: ['鱿鱼圈'],
    summary: '头足类软体动物，肉质紧实，快炒或油炸，加热过久会变硬。',
    selection: '表面光泽、肉质半透明、无异味。',
    storage: '冷藏短期、冷冻长期保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '软体动物', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '章鱼',
    aliases: ['章鱼粒'],
    category: 'SEAFOOD',
    rawNames: ['章鱼粒'],
    summary: '头足类软体动物，口感弹韧，常用作小食与配菜。',
    selection: '组织紧实、颜色自然。',
    storage: '冷藏或冷冻保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '软体动物', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '青口贝',
    aliases: ['海虹', '淡菜'],
    category: 'SEAFOOD',
    rawNames: ['青口贝'],
    summary: '双壳类软体动物，肉质鲜甜，需彻底加热且应弃去未开口的个体。',
    selection: '壳体完整闭合、无异味。',
    storage: '冷藏并尽快食用。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '软体动物', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鱼板',
    aliases: ['蒲鉾'],
    category: 'SEAFOOD',
    rawNames: ['鱼板'],
    summary: '鱼肉糜蒸制的日本鱼糕，切片即用，常作关东煮与面食配料。',
    selection: '包装完好、弹性正常。',
    storage: '冷藏保存，开封后尽快食用。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '鱼类', source: 'https://www.cfsa.net.cn/' },
      { allergen: '蛋类', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '裙带菜',
    category: 'SEAFOOD',
    rawNames: ['裙带菜'],
    summary: '褐藻类海菜，干品需泡发，常用于汤品。',
    selection: '干品色泽自然、无杂质。',
    storage: '干品密封常温存放；泡发后冷藏尽快使用。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '海带',
    aliases: ['昆布'],
    category: 'SEAFOOD',
    rawNames: ['海带'],
    summary: '大型褐藻，常作日式高汤底料，也可凉拌与炖煮。',
    selection: '干品表面带自然白霜、无霉味。',
    storage: '干品密封常温存放。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '海苔',
    aliases: ['紫菜'],
    category: 'SEAFOOD',
    rawNames: ['海苔碎', '海苔粉'],
    summary: '紫菜类海藻的加工薄片，常作点缀与调味。',
    selection: '色泽墨绿、干燥无霉味。',
    storage: '密封防潮保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '木鱼花',
    aliases: ['柴鱼片'],
    category: 'SEAFOOD',
    rawNames: ['木鱼花'],
    summary: '鲣鱼干刨成的薄片，是日式高汤（出汁）的基础原料。',
    selection: '片薄完整、香气明显、无霉味。',
    storage: '密封防潮保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '鱼类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鱼高汤',
    aliases: ['高汤'],
    category: 'SEAFOOD',
    rawNames: ['高汤'],
    summary:
      '菜谱中的“高汤”按日式鱼汤处理，即木鱼花与昆布熬制的出汁。若改用中式肉汤，风味与原料随之改变，替换需自行确认。',
    storage: '冷藏短期或冷冻保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '鱼类', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鸡高汤',
    category: 'POULTRY',
    rawNames: ['鸡高汤'],
    summary: '鸡架或鸡肉熬制的清汤，作汤底与调味用，按禽类原料对待。',
    storage: '冷藏短期或冷冻保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '豆腐',
    aliases: ['嫩豆腐', '内酯豆腐'],
    category: 'SOY',
    rawNames: ['豆腐', '嫩豆腐', '内酯豆腐'],
    summary:
      '大豆制品，质地因凝固方式不同而有别：嫩豆腐与内酯豆腐水分高、口感滑，适合蒸与汤；老豆腐更紧实，适合煎炒。',
    selection: '包装完好、无胀袋；散装应无异味与发酸。',
    storage: '冷藏保存，开封后换清水并尽快食用。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '大豆', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '豆豉',
    category: 'SOY',
    rawNames: ['豆豉'],
    summary: '发酵大豆制品，咸鲜，常用于蒸菜与炒菜调味。',
    selection: '颗粒完整、香气正常、无霉变。',
    storage: '冷藏或阴凉干燥处保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '豆瓣酱',
    aliases: ['郫县豆瓣'],
    category: 'SOY',
    rawNames: ['豆瓣酱'],
    summary: '发酵蚕豆与辣椒制成的辣酱，是川菜的重要调味基础。',
    selection: '色泽红亮、香气浓、无霉味。',
    storage: '开封后冷藏，用洁净干燥的勺子取用。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
      { allergen: '蚕豆', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '味噌',
    category: 'SOY',
    rawNames: ['味噌'],
    summary: '发酵大豆酱，咸鲜带甜，是日式汤品的核心调味。',
    selection: '包装完好、颜色均匀、无异常气味。',
    storage: '开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '鹰嘴豆',
    category: 'SOY',
    rawNames: ['鹰嘴豆', '鹰嘴豆罐头'],
    summary:
      '豆科籽粒，口感绵密，是轻食沙拉与泥酱的常见原料。罐装为熟制品，可直接使用。',
    selection: '干品颗粒饱满、无虫蛀；罐头包装完好。',
    storage: '干品密封常温；罐头开封后冷藏并尽快食用。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '魔芋丝',
    aliases: ['蒟蒻丝'],
    category: 'SOY',
    rawNames: ['魔芋丝'],
    summary: '以魔芋块茎的葡甘聚糖制成的粉丝，热量低、口感弹，需焯水后使用。',
    selection: '包装完好、无异味。',
    storage: '冷藏保存，开封后冷藏尽快食用。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '米饭',
    aliases: ['白饭'],
    category: 'GRAIN',
    rawNames: ['米饭'],
    summary: '蒸煮后的大米，主食基础。菜谱中的用量通常按熟飯计。',
    selection: '米粒饱满、无霉味与虫蛀。',
    storage: '生米密封干燥保存；熟饭冷藏并尽快食用。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '藜麦',
    category: 'GRAIN',
    rawNames: ['藜麦'],
    summary: '苋科籽粒，蛋白质与纤维丰富，口感带爽脆颗粒。',
    selection: '颗粒均匀、无杂质。',
    storage: '密封干燥保存。',
    preparation: '冲洗后按 1:2 比例加水煮至籽粒散开。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '即食燕麦',
    aliases: ['燕麦片'],
    category: 'GRAIN',
    rawNames: ['即食燕麦'],
    summary: '经压片与熟化处理的燕麦，可直接冲泡或与酸奶搭配。',
    selection: '包装完好、无结块受潮。',
    storage: '密封防潮保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '海鲜饭专用米',
    aliases: ['短粒米'],
    category: 'GRAIN',
    rawNames: ['海鲜饭专用米'],
    summary: '短粒米，吸水量高、颗粒分明，适合西班牙海鲜饭一类做法。',
    selection: '颗粒均匀、碎米少。',
    storage: '密封干燥保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '中筋面粉',
    category: 'GRAIN',
    rawNames: ['面粉', '中筋面粉'],
    summary:
      '蛋白含量中等的小麦粉，家常菜谱写「面粉」默认指它，适合面糊、上浆勾芡与家常面点。',
    selection: '颜色洁白均匀、无异味与结块。',
    storage: '密封防潮防虫保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '低筋面粉',
    category: 'GRAIN',
    rawNames: ['低筋面粉'],
    summary:
      '蛋白含量较低的小麦粉，成品松脆柔软，适合蛋糕、饼干与天妇罗类挂糊；与中筋替换会影响口感。',
    selection: '颜色洁白均匀、无异味与结块。',
    storage: '密封防潮防虫保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '面包糠',
    category: 'GRAIN',
    rawNames: ['面包糠'],
    summary: '干燥粉碎的面包屑，用于裹粉油炸。',
    selection: '干燥松散、无结块。',
    storage: '密封防潮保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '面包丁',
    aliases: ['面包块'],
    category: 'GRAIN',
    rawNames: ['面包丁'],
    summary: '切块烘烤的面包，用于沙拉等菜式的脆配料。',
    selection: '干燥酥脆、无霉味。',
    storage: '密封防潮保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '英式松饼',
    aliases: ['满芬'],
    category: 'GRAIN',
    rawNames: ['英式松饼'],
    summary: '发酵面饼，常用于早餐三明治。',
    selection: '包装完好、无霉变。',
    storage: '常温或冷冻保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '意面',
    aliases: ['意大利面', 'spaghetti'],
    category: 'GRAIN',
    rawNames: ['意面', '意大利面', '意面（如spaghetti）'],
    summary: '杜兰小麦制成的干面条，煮至弹牙后与酱汁拌合。',
    selection: '包装完好、面条无断裂受潮。',
    storage: '密封干燥保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '乌冬面',
    category: 'GRAIN',
    rawNames: ['乌冬面'],
    summary: '粗圆形的日式小麦面，口感软弹，多用于汤面。',
    selection: '包装完好、无酸味。',
    storage: '冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '拉面',
    aliases: ['日式拉面'],
    category: 'GRAIN',
    rawNames: ['拉面'],
    summary: '碱水小麦面，口感弹韧，多用于汤面。',
    selection: '包装完好、无酸败味。',
    storage: '冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '粉丝',
    category: 'GRAIN',
    rawNames: ['粉丝'],
    summary: '以绿豆或红薯淀粉制成的干粉丝，泡发后用于炒制与汤品。',
    selection: '干燥无霉、无虫蛀。',
    storage: '密封干燥保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '饺子皮',
    category: 'GRAIN',
    rawNames: ['饺子皮'],
    summary: '小麦面皮，用于包制饺子。',
    selection: '薄厚均匀、不发干开裂。',
    storage: '冷藏或冷冻保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '淀粉',
    category: 'GRAIN',
    rawNames: ['淀粉'],
    summary: '用于上浆、勾芡的纯淀粉，常见为玉米或马铃薯来源。',
    selection: '干燥细腻、无结块。',
    storage: '密封防潮保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '泡打粉',
    aliases: ['发粉'],
    category: 'GRAIN',
    rawNames: ['泡打粉'],
    summary: '化学膨松剂，用于面糊膨胀。',
    selection: '包装完好、无受潮结块。',
    storage: '密封干燥保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '藏红花',
    aliases: ['番红花'],
    category: 'GRAIN',
    rawNames: ['藏红花'],
    summary: '鸢尾科花柱头，香气特殊、上色明显，用量极少。',
    selection: '花丝暗红完整、香气浓。',
    storage: '密封避光干燥保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '盐',
    aliases: ['食盐'],
    category: 'SEASONING',
    rawNames: ['盐'],
    summary: '主要成分为氯化钠的调味品，用盐量直接影响成品咸度。',
    selection: '包装完好、无结块受潮。',
    storage: '密封防潮保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '白糖',
    aliases: ['砂糖'],
    category: 'SEASONING',
    rawNames: ['糖', '白糖'],
    summary: '结晶蔗糖，用于提鲜、上色与甜味调配。',
    selection: '干燥松散、无结块。',
    storage: '密封防潮保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '冰糖',
    category: 'SEASONING',
    rawNames: ['冰糖'],
    summary: '大颗粒蔗糖结晶，融化较慢，常用于炖煮与上色。',
    selection: '颗粒完整透明、无杂质。',
    storage: '密封防潮保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '蜂蜜',
    category: 'SEASONING',
    rawNames: ['蜂蜜'],
    summary: '蜜蜂酿制的天然甜味剂，风味随蜜源变化。',
    selection: '包装完好、无异常发酵气味。',
    storage: '阴凉干燥处存放，避免金属容器长期存放。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '酱油',
    category: 'SEASONING',
    rawNames: ['酱油'],
    summary:
      '发酵大豆与小麦制成的调味液，提供咸味与鲜味。老抽、生抽是不同工艺与用途的酱油，不视为同一种。',
    selection: '包装完好、无异常气味与沉淀。',
    storage: '开封后冷藏或阴凉处保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '生抽',
    category: 'SEASONING',
    rawNames: ['生抽'],
    summary:
      '颜色较浅、咸鲜突出的酱油，多用于调味与蘸食；与老抽不同，不可互换。',
    selection: '包装完好、色泽清亮。',
    storage: '开封后冷藏或阴凉处保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '老抽',
    category: 'SEASONING',
    rawNames: ['老抽'],
    summary: '颜色深、含焦糖色的酱油，主要用于上色；与生抽不同，不可互换。',
    selection: '包装完好、色泽深亮。',
    storage: '开封后冷藏或阴凉处保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '寿司酱油',
    category: 'SEASONING',
    rawNames: ['寿司酱油'],
    summary: '蘸食鱼生的酱油，鲜味突出、咸度较高。',
    selection: '包装完好、无异味。',
    storage: '开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '蒸鱼豉油',
    category: 'SEASONING',
    rawNames: ['蒸鱼豉油'],
    summary: '调配好的粤式调味酱油，咸鲜带甜，常用于蒸鱼。',
    selection: '包装完好、无沉淀异常。',
    storage: '开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '蚝油',
    category: 'SEASONING',
    rawNames: ['蚝油'],
    summary: '以牡蛎提取物为基料的稠状调味品，鲜味明显。',
    selection: '包装完好、无异常气味。',
    storage: '开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '贝类（牡蛎）', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '醋',
    aliases: ['米醋'],
    category: 'SEASONING',
    rawNames: ['醋'],
    summary: '发酵酸味调味品，用于提酸、解腻与腌制。',
    selection: '包装完好、无异常沉淀。',
    storage: '阴凉处密封保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '香醋',
    category: 'SEASONING',
    rawNames: ['香醋'],
    summary: '固态发酵的米醋，香气浓、酸味柔和，常用于凉拌与蘸食。',
    selection: '包装完好、香气正常。',
    storage: '阴凉处密封保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '白醋',
    category: 'SEASONING',
    rawNames: ['白醋'],
    summary: '无色醋酸溶液，酸味直接，用于腌制与清洗。',
    selection: '包装完好、无杂质。',
    storage: '密封常温保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '黑醋',
    aliases: ['黑葡萄醋', 'balsamic'],
    category: 'SEASONING',
    rawNames: ['黑醋'],
    summary: '葡萄汁发酵陈酿的深色醋，甜酸兼备，常用于凉拌与蘸汁。',
    selection: '包装完好、无沉淀异常。',
    storage: '阴凉处密封保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '红酒醋',
    category: 'SEASONING',
    rawNames: ['红酒醋'],
    summary: '红酒二次发酵酿成的果醋，酸味明亮带酒香，常用于油醋汁与腌制。',
    selection: '包装完好、无异常沉淀。',
    storage: '阴凉处密封保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '苹果醋',
    category: 'SEASONING',
    rawNames: ['苹果醋'],
    summary: '苹果汁发酵酿成的果醋，酸味柔和微甜，常用于沙拉调味。',
    selection: '包装完好、无异常沉淀。',
    storage: '阴凉处密封保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '料酒',
    category: 'SEASONING',
    rawNames: ['料酒'],
    summary: '烹饪用的低度黄酒，用于去腥增香。',
    selection: '包装完好、无酸败味。',
    storage: '阴凉处密封保存，开封后尽快用尽。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '味醂',
    aliases: ['味霖'],
    category: 'SEASONING',
    rawNames: ['味醂'],
    summary: '日式甜味米酒调味料，甜味柔和、上色光亮。',
    selection: '包装完好、颜色正常。',
    storage: '阴凉处密封保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '白葡萄酒',
    category: 'SEASONING',
    rawNames: ['白葡萄酒'],
    summary: '用于烹饪的白葡萄酒，加热后部分酒精挥发但不会完全消失。',
    selection: '包装完好、无酸化气味。',
    storage: '开封后冷藏并尽快使用。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '啤酒',
    category: 'SEASONING',
    rawNames: ['啤酒'],
    summary: '麦芽发酵酒，用于炖煮可增添麦香与微苦。',
    selection: '包装完好、在保质期内。',
    storage: '阴凉避光保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '可乐',
    category: 'SEASONING',
    rawNames: ['可乐'],
    summary: '含糖碳酸饮料，用于炖煮时提供甜味与焦糖色泽。',
    selection: '包装完好、在保质期内。',
    storage: '常温或冷藏保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '甜面酱',
    category: 'SEASONING',
    rawNames: ['甜面酱'],
    summary: '发酵小麦面粉制成的甜咸酱，常用于炒菜与蘸食。',
    selection: '质地均匀、香气正常。',
    storage: '开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '番茄酱',
    aliases: ['番茄沙司'],
    category: 'SEASONING',
    rawNames: ['番茄酱'],
    summary: '番茄浓缩调制的酱料，酸甜，用于调味与蘸食。',
    selection: '包装完好、无胀包。',
    storage: '开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '番茄罐头',
    aliases: ['罐装番茄'],
    category: 'SEASONING',
    rawNames: ['番茄罐头'],
    summary: '去皮整番茄或番茄碎罐头，风味稳定，适合炖煮。',
    selection: '罐体无膨胀变形、开罐无异味。',
    storage: '开罐后冷藏并尽快使用。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '食用油',
    aliases: ['植物油'],
    category: 'SEASONING',
    rawNames: ['食用油', '植物油', '油', '油炸用油'],
    summary:
      '植物来源的烹调用油，烟点与风味随原料不同；油炸用油指同一油品的炸制用途。',
    selection: '包装完好、无哈喇味。',
    storage: '阴凉避光密封保存；避免反复高温使用。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '橄榄油',
    category: 'SEASONING',
    rawNames: ['橄榄油'],
    summary: '压榨橄榄果实得到的油脂，初榨香气明显，适合低温烹调与凉拌。',
    selection: '包装完好、气味正常。',
    storage: '阴凉避光保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '芝麻油',
    aliases: ['香油'],
    category: 'SEASONING',
    rawNames: ['香油', '芝麻油'],
    summary: '芝麻焙炒后榨取的香气油脂，多用于出锅前提香。',
    selection: '香气浓郁、无哈喇味。',
    storage: '阴凉避光密封保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '芝麻', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '黄油',
    category: 'SEASONING',
    rawNames: ['黄油'],
    summary: '乳脂制成的固态油脂，融化后香气突出，适合煎制与烘焙。',
    selection: '包装完好、无油哈味。',
    storage: '冷藏保存；长期不用可冷冻。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '乳', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '淡奶油',
    aliases: ['稀奶油'],
    category: 'SEASONING',
    rawNames: ['淡奶油'],
    summary: '乳脂含量较高的液态奶油，用于酱汁与甜品。',
    selection: '包装完好、无结块与异味。',
    storage: '冷藏保存，开封后尽快使用。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '乳', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '牛奶',
    category: 'SEASONING',
    rawNames: ['牛奶'],
    summary: '牛乳，用于调味、炖煮与烘焙。',
    selection: '包装完好、在保质期内。',
    storage: '冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '乳', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '无糖酸奶',
    aliases: ['原味酸奶'],
    category: 'SEASONING',
    rawNames: ['无糖酸奶'],
    summary: '不额外加糖的发酵乳制品，口感偏酸，常用于早餐与沙拉。',
    selection: '包装完好、冷藏链完整。',
    storage: '冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '乳', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '蛋黄酱',
    aliases: ['美乃滋'],
    category: 'SEASONING',
    rawNames: ['蛋黄酱', '美乃滋'],
    summary: '以蛋黄与油脂乳化制成的酱料，用于沙拉与三明治。',
    selection: '包装完好、无油水分离。',
    storage: '开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '蛋类', source: 'https://www.cfsa.net.cn/' },
      { allergen: '芥末', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '凯撒酱',
    category: 'SEASONING',
    rawNames: ['凯撒酱'],
    summary: '以蛋黄酱、鳀鱼、帕玛森芝士等调制的沙拉酱，是凯撒沙拉的标志味型。',
    selection: '包装完好、无油水分离。',
    storage: '开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '蛋类', source: 'https://www.cfsa.net.cn/' },
      { allergen: '鱼类', source: 'https://www.cfsa.net.cn/' },
      { allergen: '乳', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '油醋汁',
    category: 'SEASONING',
    rawNames: ['油醋汁'],
    summary: '油与醋乳化调制的沙拉汁，酸度与油脂比例可自行调整。',
    storage: '冷藏保存，食用前摇匀。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '日式猪排酱',
    aliases: ['中浓酱'],
    category: 'SEASONING',
    rawNames: ['日式猪排酱'],
    summary: '日式果蔬风味浓稠酱汁，用于炸物蘸食。',
    selection: '包装完好、无异常气味。',
    storage: '开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '大阪烧酱',
    category: 'SEASONING',
    rawNames: ['大阪烧酱'],
    summary: '甜咸口味的日式浓稠酱汁，用于大阪烧与炒面。',
    selection: '包装完好、无异常气味。',
    storage: '开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '天妇罗蘸汁',
    aliases: ['天汁'],
    category: 'SEASONING',
    rawNames: ['天妇罗蘸汁'],
    summary: '以出汁、酱油与味醂调制的蘸汁，用于天妇罗。',
    storage: '冷藏保存，尽快使用。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '鱼类', source: 'https://www.cfsa.net.cn/' },
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '咖喱块',
    aliases: ['咖喱酱'],
    category: 'SEASONING',
    rawNames: ['咖喱块'],
    summary:
      '日式咖喱成品块，含小麦粉、油脂与香辛料。不同品牌配料不同，实际致敏成分以包装配料表为准。',
    selection: '包装完好、在保质期内。',
    storage: '阴凉干燥处密封保存，开封后密封并尽快用完。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
      { allergen: '乳', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '火锅底料',
    category: 'SEASONING',
    rawNames: ['火锅底料'],
    summary:
      '复合调味料，通常含牛油或植物油、辣椒、豆瓣酱与香辛料。不同产品配料差异大，实际致敏成分以包装配料表为准。',
    selection: '包装完好、无胀袋。',
    storage: '开封后冷藏并尽快使用。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '红油',
    aliases: ['辣椒油'],
    category: 'SEASONING',
    rawNames: ['红油', '辣椒油'],
    summary: '辣椒与油脂浸出或泼制的香辣油，用于凉菜与蘸料。',
    selection: '香气正常、无哈喇味。',
    storage: '密封阴凉处保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '花椒油',
    category: 'SEASONING',
    rawNames: ['花椒油'],
    summary: '花椒浸出的麻香油，用于凉菜与出锅提味。',
    selection: '香气明显、无哈喇味。',
    storage: '密封阴凉处保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '芝麻酱',
    aliases: ['麻酱'],
    category: 'SEASONING',
    rawNames: ['芝麻酱'],
    summary: '芝麻研磨成的稠酱，香气浓郁，需用液体调稀后使用。',
    selection: '无油层分离或分层轻微、香气正常。',
    storage: '密封阴凉处保存，开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '芝麻', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '黑胡椒',
    aliases: ['黑胡椒碎'],
    category: 'SEASONING',
    rawNames: ['黑胡椒', '黑胡椒碎'],
    summary: '胡椒科果实干燥后使用，香气随研磨后时间迅速减弱。',
    selection: '颗粒完整、香气浓。',
    storage: '密封避光保存，整粒比粉更耐存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '白胡椒粉',
    aliases: ['胡椒粉'],
    category: 'SEASONING',
    rawNames: ['白胡椒粉'],
    summary: '胡椒果实去皮后的粉末，辛香较黑胡椒柔和。',
    selection: '粉末干燥、香气正常。',
    storage: '密封避光保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '花椒',
    aliases: ['花椒粉'],
    category: 'SEASONING',
    rawNames: ['花椒', '花椒粉'],
    summary: '芸香科果实，麻味明显，是川味的基础香辛料。',
    selection: '颗粒饱满、香气浓烈、无霉味。',
    storage: '密封防潮避光保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '干辣椒',
    aliases: ['辣椒干'],
    category: 'SEASONING',
    rawNames: ['干辣椒'],
    summary: '干燥辣椒，提供辣味与香气，可整只爆香或磨粉。',
    selection: '色泽红亮、无霉斑与虫蛀。',
    storage: '密封防潮保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '泡椒',
    category: 'SEASONING',
    rawNames: ['泡椒'],
    summary: '盐渍发酵的辣椒，酸辣开胃，多用于川味炒制。',
    selection: '气味酸香、无霉变。',
    storage: '冷藏保存，取用时器具洁净。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '八角',
    aliases: ['大料'],
    category: 'SEASONING',
    rawNames: ['八角'],
    summary: '木兰科果实，香气浓郁，是炖煮类菜肴的常用香辛料。',
    selection: '瓣形完整、香气浓、无霉斑。',
    storage: '密封防潮保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '桂皮',
    aliases: ['肉桂'],
    category: 'SEASONING',
    rawNames: ['桂皮'],
    summary: '樟科树皮，甜香明显，用于炖煮与卤制。',
    selection: '卷片厚实、香气浓。',
    storage: '密封防潮保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '香叶',
    aliases: ['月桂叶'],
    category: 'SEASONING',
    rawNames: ['香叶'],
    summary: '月桂树叶干燥后使用，提供清辛香气，多在炖煮后取出。',
    selection: '叶片完整、色泽自然、香气明显。',
    storage: '密封防潮保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '干牛至',
    aliases: ['牛至'],
    category: 'SEASONING',
    rawNames: ['干牛至'],
    summary: '唇形科香草干燥品，香气浓，是意式与地中海菜式常用香料。',
    selection: '干燥、色泽自然、香气浓。',
    storage: '密封避光保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '蒜粉',
    category: 'SEASONING',
    rawNames: ['蒜粉'],
    summary: '干燥大蒜研磨成的粉，方便均匀调味。',
    selection: '干燥松散、蒜香正常。',
    storage: '密封防潮保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '熟芝麻',
    aliases: ['白芝麻'],
    category: 'SEASONING',
    rawNames: ['熟芝麻', '白芝麻'],
    summary: '焙炒过的芝麻，常用于点缀与调味。',
    selection: '香气正常、无哈喇味。',
    storage: '密封防潮保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '芝麻', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '核桃仁',
    category: 'SEASONING',
    rawNames: ['核桃仁'],
    summary: '核桃去壳后的果仁，常用于沙拉与烘焙。',
    selection: '果仁饱满、无哈喇味。',
    storage: '密封冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [
      { allergen: '坚果（核桃）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '花生米',
    aliases: ['花生'],
    category: 'SEASONING',
    rawNames: ['花生米'],
    summary: '落花生种子，可生用、炸制或磨酱。',
    selection: '颗粒饱满、无霉变与哈喇味。',
    storage: '密封防潮保存，避免受潮霉变。',
    sources: ['https://fdc.nal.usda.gov/'],
    allergens: [{ allergen: '花生', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '帕玛森芝士',
    aliases: ['帕玛森奶酪'],
    category: 'SEASONING',
    rawNames: ['帕玛森芝士'],
    summary: '意大利硬质熟成奶酪，咸鲜浓郁，多用于刨屑点缀。',
    selection: '包装完好、气味正常。',
    storage: '冷藏保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '乳', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '羊奶酪',
    aliases: ['羊乳酪', 'feta'],
    category: 'SEASONING',
    rawNames: ['羊乳酪', '羊奶酪'],
    summary: '以羊乳制成的盐渍奶酪，咸味突出、质地易碎。',
    selection: '包装完好、冷藏链完整。',
    storage: '冷藏保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [{ allergen: '乳', source: 'https://www.cfsa.net.cn/' }],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '黑橄榄',
    aliases: ['油橄榄果'],
    category: 'OTHER',
    rawNames: ['黑橄榄'],
    summary: '盐渍发酵的橄榄果实，咸香，用于沙拉与西式配菜。',
    selection: '罐体完好、无异常气味。',
    storage: '开封后冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '香蕉',
    category: 'OTHER',
    rawNames: ['香蕉'],
    summary: '芭蕉科果实，甜味突出，多用于早餐与甜品。',
    selection: '果皮转黄、无大面积黑斑与软化。',
    storage: '常温后熟；成熟后冷藏会加速表皮变黑，内部品质仍可。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '蓝莓',
    category: 'OTHER',
    rawNames: ['蓝莓'],
    summary: '杜鹃花科小浆果，酸甜清爽，多用于早餐与甜品。',
    selection: '果粒饱满、表面带自然白霜、无霉果。',
    storage: '冷藏保存，食用前再清洗。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '柠檬',
    aliases: ['柠檬汁'],
    category: 'OTHER',
    rawNames: ['柠檬', '柠檬汁'],
    summary:
      '柑橘类果实，酸味明显，用于调味、解腻与去腥。柠檬汁按同一食材处理。',
    selection: '表皮光亮、手感沉、无软塌。',
    storage: '常温或冷藏；切开后果肉包好冷藏。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '水',
    aliases: ['清水', '冰水', '凉开水', '温水'],
    category: 'OTHER',
    rawNames: ['水', '清水', '冰水', '凉开水', '温水'],
    summary:
      '饮用水。冰水、温水、凉开水按温度或处理方式区分，均为同一原料的不同状态。',
    storage: '随取随用。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '大白菜',
    aliases: ['白菜'],
    category: 'VEGETABLE',
    rawNames: [],
    summary: '叶用白菜，清甜多汁，适合炖煮与腌制。',
    selection: '叶球紧实、菜心不发黑。',
    storage: '阴凉处或冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '韭菜',
    category: 'VEGETABLE',
    rawNames: [],
    summary: '葱属叶菜，辛香突出，常用于炒蛋、做馅。',
    selection: '叶片挺立、切口新鲜不发黏。',
    storage: '冷藏；洗净后需沥干。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '火腿肠',
    aliases: ['香肠'],
    category: 'MEAT',
    rawNames: [],
    summary: '肠衣包裹的肉类乳化制品，方便加热食用。',
    selection: '包装完好、无胀袋。',
    storage: '冷藏保存。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '黄豆酱',
    aliases: ['大豆酱'],
    category: 'SOY',
    rawNames: [],
    summary: '发酵大豆制成的咸味酱，用于炒菜与蘸食。',
    selection: '质地均匀、香气正常。',
    storage: '开封后冷藏。',
    sources: ['https://www.cfsa.net.cn/'],
    allergens: [
      { allergen: '大豆', source: 'https://www.cfsa.net.cn/' },
      { allergen: '小麦（麸质）', source: 'https://www.cfsa.net.cn/' },
    ],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '葡萄干',
    category: 'OTHER',
    rawNames: [],
    summary: '葡萄干燥制品，甜味集中，用于烘焙与沙拉。',
    selection: '颗粒干燥松散、无霉变。',
    storage: '密封防潮保存。',
    sources: ['https://www.cfsa.net.cn/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '橙子',
    aliases: ['甜橙'],
    category: 'OTHER',
    rawNames: [],
    summary: '柑橘类果实，汁多味甜，可鲜食或榨汁入菜。',
    selection: '表皮紧实、手感沉。',
    storage: '常温或冷藏保存。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '苹果',
    category: 'OTHER',
    rawNames: [],
    summary: '常见仁果类水果，脆甜，可鲜食或用于沙拉与甜品。',
    selection: '表皮光滑、手感硬实、无软伤。',
    storage: '冷藏保存，避免与叶菜同放。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
  {
    reviewedAt: '2026-09-30T14:00:00+08:00',
    name: '樱桃',
    category: 'OTHER',
    rawNames: [],
    summary: '蔷薇科核果，酸甜多汁，可鲜食或点缀甜品。',
    selection: '果柄鲜绿、果皮有光泽、无软烂。',
    storage: '冷藏保存，食用前再清洗。',
    sources: ['https://fdc.nal.usda.gov/'],
  },
];
