// 人工精选菜谱（ADR-0003 的"人工打底"部分）。
// 从 seed.ts 拆出：generate-recipes 脚本需要读取现有菜名做去重与 few-shot，
// 但不能 import seed.ts（会执行 main() 拉起 DB 连接）。
import { Cuisine, Tag } from '../generated/prisma/client';

export type SeedIngredient = { name: string; amount: string };

export type SeedRecipe = {
  name: string;
  desc: string;
  cuisine: Cuisine;
  time: number;
  kcal: number;
  protein: number;
  carb: number;
  fat: number;
  img: string;
  tags: Tag[];
  ingredients: SeedIngredient[];
  steps: string[];
};

export const CURATED_RECIPES: SeedRecipe[] = [
  {
    name: '番茄罗勒意面',
    desc: '最经典的意面之一，番茄与罗勒的组合永远不出错。',
    cuisine: Cuisine.WESTERN,
    time: 25,
    kcal: 520,
    protein: 14,
    carb: 78,
    fat: 16,
    img: '/assets/pasta.png',
    tags: [Tag.VEGETARIAN, Tag.QUICK],
    ingredients: [
      { name: '意面', amount: '200g' },
      { name: '番茄', amount: '3个' },
      { name: '罗勒', amount: '一小把' },
      { name: '大蒜', amount: '2瓣' },
      { name: '橄榄油', amount: '2汤匙' },
      { name: '盐', amount: '适量' },
      { name: '黑胡椒', amount: '适量' },
    ],
    steps: [
      '烧一锅水加盐煮意面至弹牙',
      '同时热橄榄油爆香蒜片',
      '下番茄丁炒至出汁',
      '拌入煮好的意面与罗勒',
      '撒盐与黑胡椒调味',
    ],
  },
  {
    name: '香煎三文鱼配时蔬',
    desc: '高蛋白低碳的一餐，鱼皮煎脆是关键。',
    cuisine: Cuisine.WESTERN,
    time: 20,
    kcal: 480,
    protein: 42,
    carb: 8,
    fat: 30,
    img: '/assets/salmon.jpg',
    tags: [Tag.HIGH_PROTEIN, Tag.LOW_CARB],
    ingredients: [
      { name: '三文鱼', amount: '1块(约150g)' },
      { name: '芦笋', amount: '一把' },
      { name: '柠檬', amount: '半个' },
      { name: '橄榄油', amount: '1汤匙' },
      { name: '盐', amount: '适量' },
      { name: '黑胡椒', amount: '适量' },
    ],
    steps: [
      '三文鱼擦干、两面撒盐黑胡椒',
      '热锅少油鱼皮朝下煎脆',
      '翻面煎至中心半熟',
      '芦笋另锅快炒至断生',
      '挤柠檬汁装盘',
    ],
  },
  {
    name: '日式咖喱鸡饭',
    desc: '浓郁暖胃，剩一锅第二天更入味。',
    cuisine: Cuisine.JAPANESE,
    time: 35,
    kcal: 640,
    protein: 28,
    carb: 85,
    fat: 22,
    img: '/assets/curry.jpg',
    tags: [Tag.COMFORTING],
    ingredients: [
      { name: '鸡腿肉', amount: '2只' },
      { name: '土豆', amount: '1个' },
      { name: '胡萝卜', amount: '1根' },
      { name: '洋葱', amount: '1个' },
      { name: '咖喱块', amount: '半盒(约100g)' },
      { name: '米饭', amount: '2碗' },
    ],
    steps: [
      '鸡肉切块焯水去腥',
      '洋葱炒香至透明',
      '下土豆胡萝卜翻炒',
      '加水煮至蔬菜软烂',
      '关火放入咖喱块融化，浇在米饭上',
    ],
  },
  {
    name: '藜麦牛油果碗',
    desc: '一碗补齐碳水、蛋白与健康脂肪。',
    cuisine: Cuisine.LIGHT,
    time: 15,
    kcal: 410,
    protein: 14,
    carb: 45,
    fat: 20,
    img: '/assets/bowl.jpg',
    tags: [Tag.VEGETARIAN, Tag.HIGH_PROTEIN, Tag.LOW_CAL],
    ingredients: [
      { name: '藜麦', amount: '1杯' },
      { name: '牛油果', amount: '1个' },
      { name: '鹰嘴豆', amount: '半杯' },
      { name: '菠菜', amount: '一把' },
      { name: '柠檬', amount: '半个' },
      { name: '橄榄油', amount: '1汤匙' },
    ],
    steps: [
      '藜麦煮熟沥干',
      '鹰嘴豆与菠菜快速焯烫',
      '所有食材码入碗中',
      '牛油果切片摆上',
      '淋柠檬汁与橄榄油',
    ],
  },
  {
    name: '西红柿炒鸡蛋',
    desc: '国民下饭菜，十分钟搞定。',
    cuisine: Cuisine.HOME,
    time: 10,
    kcal: 300,
    protein: 14,
    carb: 12,
    fat: 22,
    img: '',
    tags: [Tag.QUICK],
    ingredients: [
      { name: '番茄', amount: '2个' },
      { name: '鸡蛋', amount: '3个' },
      { name: '葱', amount: '2根' },
      { name: '盐', amount: '适量' },
      { name: '糖', amount: '少许' },
      { name: '食用油', amount: '2汤匙' },
    ],
    steps: [
      '鸡蛋打散炒熟盛出',
      '西红柿切块下锅炒至出汁',
      '加少许糖提鲜',
      '倒回鸡蛋翻炒均匀',
      '撒葱花出锅',
    ],
  },
  {
    name: '蒜蓉蒸豆腐',
    desc: '清淡鲜嫩，减脂期友好。',
    cuisine: Cuisine.HOME,
    time: 18,
    kcal: 220,
    protein: 14,
    carb: 10,
    fat: 14,
    img: '',
    tags: [Tag.VEGETARIAN, Tag.LOW_CAL],
    ingredients: [
      { name: '嫩豆腐', amount: '1块' },
      { name: '大蒜', amount: '4瓣' },
      { name: '葱花', amount: '适量' },
      { name: '酱油', amount: '2汤匙' },
      { name: '香油', amount: '1茶匙' },
    ],
    steps: ['豆腐切块装盘入锅蒸8分钟', '蒜蓉用热油泼香', '淋酱油与香油', '撒葱花'],
  },
  {
    name: '照烧鸡腿饭',
    desc: '甜咸适口，便当党最爱。',
    cuisine: Cuisine.JAPANESE,
    time: 25,
    kcal: 560,
    protein: 32,
    carb: 65,
    fat: 18,
    img: '',
    tags: [Tag.HIGH_PROTEIN],
    ingredients: [
      { name: '鸡腿肉', amount: '1只' },
      { name: '酱油', amount: '3汤匙' },
      { name: '味醂', amount: '3汤匙' },
      { name: '糖', amount: '1汤匙' },
      { name: '米饭', amount: '1碗' },
      { name: '姜', amount: '2片' },
    ],
    steps: [
      '鸡腿去骨擦干',
      '皮朝下煎至金黄',
      '翻面煎熟',
      '酱油味醂糖调汁收浓',
      '切块盖在米饭上',
    ],
  },
  {
    name: '凯撒沙拉',
    desc: '清爽开胃，主食前的小仪式。',
    cuisine: Cuisine.WESTERN,
    time: 15,
    kcal: 380,
    protein: 10,
    carb: 22,
    fat: 28,
    img: '',
    tags: [Tag.LOW_CAL, Tag.QUICK],
    ingredients: [
      { name: '罗马生菜', amount: '1棵' },
      { name: '面包丁', amount: '1把' },
      { name: '帕玛森芝士', amount: '适量' },
      { name: '凯撒酱', amount: '3汤匙' },
      { name: '柠檬', amount: '半个' },
    ],
    steps: [
      '生菜洗净沥干撕成小块',
      '面包切丁烤脆',
      '生菜拌凯撒酱',
      '撒面包丁与芝士碎',
      '挤柠檬汁',
    ],
  },
  {
    name: '麻婆豆腐',
    desc: '麻辣鲜香烫，一碗饭不够。',
    cuisine: Cuisine.SICHUAN,
    time: 20,
    kcal: 340,
    protein: 16,
    carb: 14,
    fat: 24,
    img: '',
    tags: [Tag.RICE_FRIENDLY],
    ingredients: [
      { name: '嫩豆腐', amount: '1块' },
      { name: '猪肉末', amount: '150g' },
      { name: '豆瓣酱', amount: '1.5汤匙' },
      { name: '花椒', amount: '1茶匙' },
      { name: '葱花', amount: '适量' },
      { name: '蒜', amount: '2瓣' },
    ],
    steps: [
      '豆腐切块焯水定型',
      '肉末炒至变色',
      '下豆瓣酱炒出红油',
      '加豆腐炖煮入味',
      '勾芡撒花椒面葱花',
    ],
  },
  {
    name: '味噌汤',
    desc: '日料餐桌的暖场，三分钟。',
    cuisine: Cuisine.JAPANESE,
    time: 12,
    kcal: 120,
    protein: 8,
    carb: 10,
    fat: 4,
    img: '',
    tags: [Tag.LOW_CAL, Tag.QUICK],
    ingredients: [
      { name: '味噌', amount: '2汤匙' },
      { name: '豆腐', amount: '半块' },
      { name: '海带', amount: '1片' },
      { name: '葱花', amount: '适量' },
      { name: '裙带菜', amount: '1把' },
    ],
    steps: ['水烧开下裙带菜与豆腐', '味噌用少量汤化开倒入', '小火不再煮沸', '撒葱花'],
  },
  {
    name: '土豆炖牛肉',
    desc: '慢炖出味，冬天的一锅满足。',
    cuisine: Cuisine.HOME,
    time: 45,
    kcal: 520,
    protein: 35,
    carb: 30,
    fat: 28,
    img: '',
    tags: [Tag.HIGH_PROTEIN, Tag.COMFORTING],
    ingredients: [
      { name: '牛腩', amount: '400g' },
      { name: '土豆', amount: '2个' },
      { name: '胡萝卜', amount: '1根' },
      { name: '洋葱', amount: '1个' },
      { name: '酱油', amount: '3汤匙' },
      { name: '八角', amount: '2颗' },
    ],
    steps: [
      '牛腩切块焯水',
      '炒香洋葱下牛肉',
      '加酱油与水炖40分钟',
      '下土豆胡萝卜炖至软烂',
      '收汁',
    ],
  },
  {
    name: '凉拌黄瓜',
    desc: '开胃凉菜，酸辣脆爽。',
    cuisine: Cuisine.SICHUAN,
    time: 8,
    kcal: 80,
    protein: 2,
    carb: 8,
    fat: 5,
    img: '',
    tags: [Tag.LOW_CAL, Tag.QUICK, Tag.VEGETARIAN],
    ingredients: [
      { name: '黄瓜', amount: '2根' },
      { name: '大蒜', amount: '3瓣' },
      { name: '醋', amount: '2汤匙' },
      { name: '辣椒油', amount: '1汤匙' },
      { name: '盐', amount: '适量' },
    ],
    steps: ['黄瓜拍裂切段', '蒜蓉与调料调汁', '拌匀冷藏10分钟更入味'],
  },
  /* ---- Phase 2 人工精选补充（ADR-0003 打底） ---- */
  {
    name: '青椒肉丝',
    desc: '家常快手小炒，下饭一绝。',
    cuisine: Cuisine.HOME,
    time: 15,
    kcal: 380,
    protein: 22,
    carb: 10,
    fat: 27,
    img: '',
    tags: [Tag.QUICK, Tag.RICE_FRIENDLY],
    ingredients: [
      { name: '猪里脊', amount: '200g' },
      { name: '青椒', amount: '2个' },
      { name: '大蒜', amount: '2瓣' },
      { name: '生抽', amount: '1汤匙' },
      { name: '淀粉', amount: '1茶匙' },
      { name: '食用油', amount: '2汤匙' },
    ],
    steps: [
      '里脊切丝，加生抽与淀粉抓匀腌10分钟',
      '青椒去籽切丝，蒜切片',
      '热锅快炒肉丝至变色盛出',
      '爆香蒜片，下青椒大火快炒',
      '回锅肉丝翻匀，调味出锅',
    ],
  },
  {
    name: '可乐鸡翅',
    desc: '甜亮酱香的哄娃神器，零失败。',
    cuisine: Cuisine.HOME,
    time: 30,
    kcal: 450,
    protein: 30,
    carb: 28,
    fat: 22,
    img: '',
    tags: [Tag.COMFORTING],
    ingredients: [
      { name: '鸡翅中', amount: '8个' },
      { name: '可乐', amount: '1罐(330ml)' },
      { name: '生抽', amount: '2汤匙' },
      { name: '姜', amount: '3片' },
      { name: '料酒', amount: '1汤匙' },
    ],
    steps: [
      '鸡翅两面划刀，加料酒姜片焯水',
      '少油煎至两面金黄',
      '倒入可乐与生抽，没过鸡翅',
      '中小火焖15分钟',
      '大火收汁至浓稠挂亮',
    ],
  },
  {
    name: '手撕包菜',
    desc: '大火快炒的镬气素菜。',
    cuisine: Cuisine.HOME,
    time: 12,
    kcal: 180,
    protein: 5,
    carb: 14,
    fat: 12,
    img: '',
    tags: [Tag.QUICK, Tag.VEGETARIAN, Tag.LOW_CAL],
    ingredients: [
      { name: '包菜', amount: '半颗' },
      { name: '干辣椒', amount: '3个' },
      { name: '大蒜', amount: '3瓣' },
      { name: '生抽', amount: '1汤匙' },
      { name: '醋', amount: '1茶匙' },
      { name: '食用油', amount: '1.5汤匙' },
    ],
    steps: [
      '包菜手撕成片，洗净沥干',
      '热油爆香干辣椒与蒜片',
      '下包菜大火爆炒2分钟',
      '沿锅边淋生抽与醋，翻匀出锅',
    ],
  },
  {
    name: '番茄蛋花汤',
    desc: '十分钟上桌的国民汤。',
    cuisine: Cuisine.HOME,
    time: 10,
    kcal: 120,
    protein: 7,
    carb: 8,
    fat: 7,
    img: '',
    tags: [Tag.QUICK, Tag.LOW_CAL],
    ingredients: [
      { name: '番茄', amount: '1个' },
      { name: '鸡蛋', amount: '2个' },
      { name: '香油', amount: '1茶匙' },
      { name: '盐', amount: '适量' },
      { name: '葱花', amount: '适量' },
    ],
    steps: [
      '番茄切块炒出沙，加水烧开',
      '鸡蛋打散，转圈淋入锅中',
      '蛋花浮起即关火，盐调味',
      '滴香油撒葱花',
    ],
  },
  {
    name: '回锅肉',
    desc: '川菜头牌，灯盏窝才算合格。',
    cuisine: Cuisine.SICHUAN,
    time: 25,
    kcal: 520,
    protein: 24,
    carb: 12,
    fat: 40,
    img: '',
    tags: [Tag.RICE_FRIENDLY],
    ingredients: [
      { name: '五花肉', amount: '300g' },
      { name: '蒜苗', amount: '1把' },
      { name: '豆瓣酱', amount: '1.5汤匙' },
      { name: '甜面酱', amount: '1茶匙' },
      { name: '姜', amount: '3片' },
    ],
    steps: [
      '五花肉冷水下锅加姜煮15分钟，晾凉切薄片',
      '少油中小火煸肉片至微卷出油',
      '下豆瓣酱与甜面酱炒出红油',
      '下蒜苗梗炒断生，再下蒜苗叶',
      '翻匀出锅',
    ],
  },
  {
    name: '宫保鸡丁',
    desc: '糊辣荔枝口，花生脆是灵魂。',
    cuisine: Cuisine.SICHUAN,
    time: 20,
    kcal: 420,
    protein: 28,
    carb: 18,
    fat: 26,
    img: '',
    tags: [Tag.RICE_FRIENDLY],
    ingredients: [
      { name: '鸡腿肉', amount: '250g' },
      { name: '花生米', amount: '1把' },
      { name: '干辣椒', amount: '5个' },
      { name: '花椒', amount: '1茶匙' },
      { name: '葱', amount: '1根' },
      { name: '生抽', amount: '2汤匙' },
      { name: '醋', amount: '1汤匙' },
      { name: '糖', amount: '1茶匙' },
    ],
    steps: [
      '鸡腿切丁，加生抽淀粉腌10分钟',
      '生抽醋糖调成碗汁',
      '热油小火炸香花椒与干辣椒',
      '下鸡丁大火滑炒至变色',
      '淋碗汁收汁，下花生米葱段翻匀',
    ],
  },
  {
    name: '鱼香茄子',
    desc: '无鱼有鱼香，软糯下饭。',
    cuisine: Cuisine.SICHUAN,
    time: 18,
    kcal: 260,
    protein: 6,
    carb: 20,
    fat: 17,
    img: '',
    tags: [Tag.VEGETARIAN, Tag.RICE_FRIENDLY],
    ingredients: [
      { name: '茄子', amount: '2根' },
      { name: '大蒜', amount: '3瓣' },
      { name: '姜', amount: '1片' },
      { name: '豆瓣酱', amount: '1汤匙' },
      { name: '醋', amount: '1汤匙' },
      { name: '糖', amount: '1汤匙' },
      { name: '生抽', amount: '1汤匙' },
    ],
    steps: [
      '茄子切条，盐腌10分钟挤掉水分',
      '醋糖生抽加少量水调成鱼香汁',
      '多油把茄子煸软盛出',
      '爆香姜蒜与豆瓣酱',
      '回锅茄子淋汁，大火翻匀收汁',
    ],
  },
  {
    name: '亲子丼',
    desc: '鸡肉与蛋的温柔盖饭。',
    cuisine: Cuisine.JAPANESE,
    time: 20,
    kcal: 550,
    protein: 30,
    carb: 60,
    fat: 18,
    img: '',
    tags: [Tag.COMFORTING],
    ingredients: [
      { name: '鸡腿肉', amount: '1只' },
      { name: '鸡蛋', amount: '2个' },
      { name: '洋葱', amount: '半个' },
      { name: '酱油', amount: '2汤匙' },
      { name: '味醂', amount: '2汤匙' },
      { name: '米饭', amount: '1碗' },
    ],
    steps: [
      '鸡腿去骨切块，洋葱切丝',
      '酱油味醂加等量水煮开，下洋葱与鸡肉',
      '中火煮6分钟至鸡肉熟透',
      '蛋液淋面，半凝固即关火',
      '整锅滑到热米饭上',
    ],
  },
  {
    name: '厚蛋烧',
    desc: '层层卷起的高汤蛋香。',
    cuisine: Cuisine.JAPANESE,
    time: 15,
    kcal: 280,
    protein: 15,
    carb: 6,
    fat: 22,
    img: '',
    tags: [Tag.QUICK, Tag.VEGETARIAN],
    ingredients: [
      { name: '鸡蛋', amount: '4个' },
      { name: '糖', amount: '1汤匙' },
      { name: '酱油', amount: '1茶匙' },
      { name: '食用油', amount: '适量' },
    ],
    steps: [
      '鸡蛋加糖酱油打散，过筛更细',
      '方锅刷薄油，倒一层蛋液',
      '半凝固时从一端卷起推至锅边',
      '重复倒液卷起至蛋液用完',
      '出锅切块',
    ],
  },
  {
    name: '姜汁烧肉',
    desc: '日式定食店的人气王。',
    cuisine: Cuisine.JAPANESE,
    time: 15,
    kcal: 400,
    protein: 26,
    carb: 12,
    fat: 27,
    img: '',
    tags: [Tag.QUICK, Tag.HIGH_PROTEIN],
    ingredients: [
      { name: '猪里脊片', amount: '200g' },
      { name: '姜', amount: '1块' },
      { name: '酱油', amount: '2汤匙' },
      { name: '味醂', amount: '1汤匙' },
      { name: '洋葱', amount: '半个' },
      { name: '食用油', amount: '1汤匙' },
    ],
    steps: [
      '姜磨成泥，与酱油味醂调成姜汁',
      '洋葱切丝炒软',
      '肉片大火煎至两面微焦',
      '淋姜汁翻炒裹匀即可',
    ],
  },
  {
    name: '蒜香黄油虾',
    desc: '十五分钟的高级感。',
    cuisine: Cuisine.WESTERN,
    time: 15,
    kcal: 320,
    protein: 28,
    carb: 4,
    fat: 22,
    img: '',
    tags: [Tag.QUICK, Tag.HIGH_PROTEIN, Tag.LOW_CARB],
    ingredients: [
      { name: '虾仁', amount: '200g' },
      { name: '黄油', amount: '20g' },
      { name: '大蒜', amount: '4瓣' },
      { name: '柠檬', amount: '半个' },
      { name: '欧芹', amount: '少许' },
      { name: '盐', amount: '适量' },
    ],
    steps: [
      '虾仁开背去线，擦干水分',
      '黄油融化，小火炒香蒜末',
      '下虾仁中大火煎至变色卷曲',
      '盐调味，挤柠檬汁，撒欧芹',
    ],
  },
  {
    name: '奶油蘑菇意面',
    desc: '奶香裹满每一根面条。',
    cuisine: Cuisine.WESTERN,
    time: 25,
    kcal: 580,
    protein: 16,
    carb: 70,
    fat: 26,
    img: '',
    tags: [Tag.VEGETARIAN, Tag.COMFORTING],
    ingredients: [
      { name: '意面', amount: '200g' },
      { name: '口蘑', amount: '150g' },
      { name: '淡奶油', amount: '100ml' },
      { name: '大蒜', amount: '2瓣' },
      { name: '黄油', amount: '15g' },
      { name: '帕玛森芝士', amount: '适量' },
    ],
    steps: [
      '意面加盐煮至弹牙，留一杯面汤',
      '黄油炒香蒜片，下口蘑炒出水汽',
      '倒淡奶油煮开，下意面',
      '加面汤调节浓稠',
      '撒芝士碎拌匀',
    ],
  },
  {
    name: '香煎鸡胸配烤蔬菜',
    desc: '健身餐也可以不委屈。',
    cuisine: Cuisine.WESTERN,
    time: 30,
    kcal: 380,
    protein: 40,
    carb: 15,
    fat: 17,
    img: '',
    tags: [Tag.HIGH_PROTEIN, Tag.LOW_CARB],
    ingredients: [
      { name: '鸡胸肉', amount: '1块(约180g)' },
      { name: '彩椒', amount: '1个' },
      { name: '西葫芦', amount: '半根' },
      { name: '橄榄油', amount: '1汤匙' },
      { name: '黑胡椒', amount: '适量' },
      { name: '盐', amount: '适量' },
    ],
    steps: [
      '鸡胸横剖成两片，盐黑胡椒腌10分钟',
      '蔬菜切块拌橄榄油，200°C烤15分钟',
      '鸡胸中火每面煎4分钟',
      '关火盖盖焖3分钟锁汁',
      '切片配烤蔬菜装盘',
    ],
  },
  {
    name: '鸡胸肉沙拉',
    desc: '高蛋白低卡的一盆满足。',
    cuisine: Cuisine.LIGHT,
    time: 15,
    kcal: 300,
    protein: 32,
    carb: 12,
    fat: 13,
    img: '',
    tags: [Tag.HIGH_PROTEIN, Tag.LOW_CAL, Tag.QUICK],
    ingredients: [
      { name: '鸡胸肉', amount: '1块' },
      { name: '混合生菜', amount: '1把' },
      { name: '小番茄', amount: '6个' },
      { name: '黄瓜', amount: '半根' },
      { name: '橄榄油', amount: '1汤匙' },
      { name: '黑醋', amount: '1汤匙' },
    ],
    steps: [
      '鸡胸水开后小火煮10分钟，焖5分钟',
      '撕成条或切片',
      '蔬菜洗净切块铺底',
      '码上鸡肉，淋橄榄油与黑醋',
    ],
  },
  {
    name: '虾仁蒸蛋',
    desc: '镜面般滑嫩的温柔蛋白。',
    cuisine: Cuisine.LIGHT,
    time: 18,
    kcal: 220,
    protein: 20,
    carb: 6,
    fat: 13,
    img: '',
    tags: [Tag.HIGH_PROTEIN, Tag.LOW_CAL],
    ingredients: [
      { name: '鸡蛋', amount: '3个' },
      { name: '虾仁', amount: '8只' },
      { name: '温水', amount: '蛋液的1.5倍' },
      { name: '生抽', amount: '1茶匙' },
      { name: '香油', amount: '几滴' },
    ],
    steps: [
      '鸡蛋加温水打匀过筛，盖保鲜膜',
      '水开后中火蒸8分钟',
      '铺上虾仁再蒸3分钟',
      '淋生抽与香油',
    ],
  },
  {
    name: '酸奶水果燕麦碗',
    desc: '五分钟搞定的清爽早餐。',
    cuisine: Cuisine.LIGHT,
    time: 5,
    kcal: 320,
    protein: 14,
    carb: 48,
    fat: 9,
    img: '',
    tags: [Tag.VEGETARIAN, Tag.QUICK, Tag.LOW_CAL],
    ingredients: [
      { name: '即食燕麦', amount: '50g' },
      { name: '无糖酸奶', amount: '200g' },
      { name: '香蕉', amount: '1根' },
      { name: '蓝莓', amount: '1把' },
      { name: '蜂蜜', amount: '1茶匙' },
    ],
    steps: ['燕麦铺碗底，倒上酸奶', '香蕉切片与蓝莓码上', '淋蜂蜜即可'],
  },
];
